"{\
	'general':\
	{\
		'name':'Device',\
		'instance':1,\
		'interval':5000\
	},\
	'components':[\
		{\
			'name':'Analog',\
			'params':'default'\
		},\
    {\
      'name':'MAX31856',\
      'params':['Top Probe', 1, 11, 10, 11, 12, 13]\
    },\
    {\
      'name':'MAX31856',\
      'params':['Bottom Probe', 1, 18, 10, 11, 12, 13]\
    },\
    {\
      'name':'MAX31856',\
      'params':['Top Probe Averaged', 100, 11, 10, 11, 12, 13]\
    },\
    {\
      'name':'MAX31856',\
      'params':['Bottom Probe Averaged', 100, 18, 10, 11, 12, 13]\
    },\
    {\
      'name':'Relay',\
      'params':[\
        13\
      ]\
    },\
		{\
			'name':'SD',\
			'params':[true,1000,10,'datafile.csv']\
		},\
		{\
			'name':'DS3231',\
			'params':'default'\
		},\
   {\
    'name':'Loom_Interrupt_Manager',\
    'params':[13]\
   },\
   {\
   'name':'Loom_Sleep_Manager',\
    'params':[true,false,1]\
    }\
	]\
}"
