SapFlow Probe: measure.h File Reference
measure.h File Reference
#include "pinout.h"
#include "schedule.h"
#include "sd_log.h"
#include <Adafruit_MAX31865.h>
Data Structures
struct temperature
Stores a tuple of temperature values.
Macros
#define Rnom 100.0
Nominal RTD resistance in ohms.
#define Rref 430.0
Nominal reference resistor in ohms.
Functions
int measure (struct pt *pt=&measure_thd)
Captures a measurement from the three probes.
int sample_timer (struct pt *pt=&sample_timer_thd)
Controls timing of the measurements.
int baseline (struct pt *pt=&baseline_thd)
Calculates baseline temperature.
int delta (struct pt *pt=&delta_thd)
Calculates temperature delta and sapflow.
Variables
static bool sample_trigger
global flag for synchronizing live data processing. Set by sample_timer()
static struct temperature latest
The most recent temperature reading, measured by the measure() protothread.
static struct temperature reference
The baseline temperature reading, computed by the baseline() protothread.
static struct pt measure_thd
Protothread control structure for measure()
static struct pt sample_timer_thd
Protothread control structure for sample_timer()
static struct pt baseline_thd
Protothread control structure for baseline()
static struct pt delta_thd
Protothread control structure for delta()
Function Documentation
baseline()
int baseline (struct pt * pt = &baseline_thd)
Calculates baseline temperature.
This is a protothread that averages 10 samples of data to determine the "initial" or "baseline" temperature of the tree. It should be used before the heater is turned on.
Parameters
pt A pointer to the protothread control structure. The default parameter is correct. Don't forget to initialize the control structure in setup().
Returns
the status of the protothread (Waiting, yeilded, exited, or ended)
Definition at line 65 of file measure.cpp.
References temperature::lower, reference, and temperature::upper.
Referenced by schedule().
delta()
int delta (struct pt * pt = &delta_thd)
Calculates temperature delta and sapflow.
This is a protothread that calculates the sap flow by averaging measurements over 40 seconds. It also calls other functions to get the weight, package the data, log to an SD card, and send the information over LoRa.
Parameters
pt A pointer to the protothread control structure. The default parameter is correct. Don't forget to initialize the control structure in setup().
Returns
the status of the protothread (Waiting, yeilded, exited, or ended)
We compute sapflow using the following formula:: sapflow = k / x * log(v1 / v2) / 3600
k is an empirical constant
x is the distance between the probes
v1 is temperature increase of the upper probe from its baseline temperature
v2 is the temperature increase of the lower probe from its baseline temperature
3600 is the number of seconds in an hour
In order to get a smoother result, we are takng the average of this calculation over a period of 40 seconds. Burges et. al. (2001) suggests that this value should converge.
Definition at line 91 of file measure.cpp.
References build_msg(), cout(), latest, lora_init(), temperature::lower, reference, rtc_ds, sample_trigger, and temperature::upper.
Referenced by schedule().
measure()
int measure (struct pt * pt = &measure_thd)
Captures a measurement from the three probes.
This is a protothread that reads the temperature from three RTD amplifiers connected to the probes in the tree. It stores the result in the global variable "latest", and logs to the SD card.
Parameters
pt A pointer to the protothread control structure. The default parameter is correct. Don't forget to initialize the control structure in setup().
Returns
the status of the protothread (Waiting, yeilded, exited, or ended)
Definition at line 22 of file measure.cpp.
References temperature::heater, HEATER_CS, latest, temperature::lower, LOWER_CS, Rnom, Rref, sample_trigger, temperature::upper, and UPPER_CS.
Referenced by loop().
sample_timer()
int sample_timer (struct pt * pt = &sample_timer_thd)
Controls timing of the measurements.
This is a protothread that creates a pulse every second on the global variable sample_trigger in order to sychronize sample-based processing. Protothreads that sample or process sampled data can latch this signal using PT_WAIT_UNTIL(pt, sample_trigger); PT_WAIT_WHILE(pt, sample_trigger); to synchronize execution without impacting the sample frequency.
Parameters
pt A pointer to the protothread control structure. The default parameter is correct. Don't forget to initialize the control structure in setup().
Returns
the status of the protothread (Waiting, yeilded, exited, or ended)
Definition at line 8 of file measure.cpp.
References sample_trigger.
Referenced by loop().