SapFlow Probe: pinout.cpp File Reference
pinout.cpp File Reference
#include "pinout.h"
#include "sd_log.h"
Functions
void hardware_init (void)
Initializes the hardware.
void hardware_deinit (void)
De-initializes hardware.
Function Documentation
hardware_deinit()
void hardware_deinit (void)
De-initializes hardware.
Used before sleeping to save power
References EN_3v3, EN_5v, SD_CS, SPI_MOSI, SPI_SCK, and STATUS_LED.
Referenced by feather_sleep().
hardware_init()
void hardware_init (void)
Initializes the hardware.
Used at startup or when waking from sleep
References EN_3v3, EN_5v, HEATER, I2C_SCL, I2C_SDA, RFM95_CS, sd, SD_CS, SPI_MOSI, SPI_SCK, and STATUS_LED.
Referenced by feather_sleep(), and setup().