SapFlow Probe: schedule.h File Reference
schedule.h File Reference
#include <OPEnS_RTC.h>
#include <LowPower.h>
#include "pinout.h"
#include "measure.h"
Functions
void alarmISR (void)
Interrupt handler for RTC alarm.
void feather_sleep (void)
Maximizes power savings during sleep.
void sleep_cycle (int interval=5)
Sleep function for periodic sleeping.
int schedule (struct pt *pt=&sched_thd)
Controls general measurement schedule.
Variables
static struct pt sched_thd
Protothread control structure for measure()
static RTC_DS3231 rtc_ds
Instance of our real-time clock.
static bool sleep
Global flag to prep for sleep.
Function Documentation
alarmISR()
void alarmISR (void)
Interrupt handler for RTC alarm.
Called when the feather wakes up from sleep. Disables the RTC interrupt.
Definition at line 5 of file schedule.cpp.
References ALARM_PIN, and rtc_ds.
Referenced by feather_sleep().
feather_sleep()
void feather_sleep (void)
Maximizes power savings during sleep.
Steps for going to sleep:
Attach interrupt to RTC pin
Disconnect from the SD card
Disconnect from Serial and USB
Turn off power rails and status LED
Begin deep sleep
Steps for waking up:
Attach USB and Serial
Turn on power rails and status LED
Open SD card
Definition at line 13 of file schedule.cpp.
References ALARM_PIN, alarmISR(), EN_3v3, EN_5v, sd, SD_CS, SPI_MOSI, SPI_SCK, and STATUS_LED.
Referenced by sleep_cycle().
schedule()
int schedule (struct pt * pt = &sched_thd)
Controls general measurement schedule.
This is the schedule:
Measure temperature of tree (before heat is applied)
Apply heat pulse
Wait for the peak of the heat to reach the upper and lower probes.
Measure the sap flow
Sleep until next measurement cycle
Parameters
pt A pointer to the protothread control structure. The default parameter is correct. Don't forget to initialize the control structure in setup().
Returns
the status of the protothread (Waiting, yeilded, exited, or ended)
Definition at line 80 of file schedule.cpp.
References baseline(), delta(), HEATER, rtc_ds, sleep, and sleep_cycle().
Referenced by loop().
sleep_cycle()
void sleep_cycle (int interval = 5)
Sleep function for periodic sleeping.
Sleep until the time is a round multiple of the minute inteval. Produces unexpected bevahior for non-factors of 60 (7, 8, 9, 11, etc). For example, if it's 5:39 and you select an interval of 15, the microcontroller will wake up at 5:45, since 3*15 = 45. This function internally calls feather_sleep() to handle prep and resume from sleeping
Parameters
interval The increment to sleep for.
Definition at line 66 of file schedule.cpp.
References feather_sleep(), and rtc_ds.
Referenced by schedule().